version: "3.8"

services:
  setup:
    image: ${SETUP_IMAGE}
    networks:
      - ESIEM_Network
    extra_hosts:
      - "${CLIENT_DOMAIN}:${ESIEM_IP01}"
    environment:
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ELASTIC_USER=${ELASTIC_USER}
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == ${SWARM_HOSTNAME}

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    hostname: kibana01.${CLIENT_DOMAIN}
    networks:
      - ESIEM_Network
    extra_hosts:
      - "${CLIENT_DOMAIN}:${ESIEM_IP01}"
    volumes:
      - kibanadata:/usr/share/kibana/data
      - ./Kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ${CERTS_DIR}:/usr/share/kibana/config/certs:ro
      - ${CERTS_isrgrootx1}:/certs/isrgrootx.pem:ro
    ports:
      - target: 5601
        published: ${KIBANA_PORT}
        protocol: tcp
        mode: host
    environment:
      - SERVERNAME=kibana
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTICSEARCH_HOSTS=https://es01.${CLIENT_DOMAIN}:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
      - ROOT_DOMAIN=esiem.io
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/certs/isrgrootx.pem
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/privkey.pem
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/fullchain.pem
      - SERVER_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/fullchain.pem
      - TZ=${TZ}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == ${SWARM_HOSTNAME}
      resources:
        limits:
          memory: ${KIBANA_MEM_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl -sk -I https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 10s
      timeout: 30s
      retries: 120

networks:
  ESIEM_Network:
    external: true
    name: ESIEM_Network

volumes:
  kibanadata:
    driver: local