version: "3.8"

services:
  scheduler:
    image: esiem/scheduler-vault:${STACK_VERSION}
    hostname: scheduler.${CLIENT_DOMAIN}

    networks:
      - ESIEM_Network

    secrets:
      - vault_addr
      - vault_secret_path
      - vault_token

    volumes:
      - /ESIEM/ESIEM_CORE/Logstash/pipeline/EnrichmentFiles:/usr/share/logstash/pipeline/EnrichmentFiles
      - /ESIEM/ESIEM_CORE/Scheduler:/Scheduler
      - ${ES_BACKUP}:/Backups
      - ${Certs}:/Certs

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: ${SCHEDULER_MEM_LIMIT}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  ESIEM_Network:
    external: true

secrets:
  vault_addr:
    external: true

  vault_secret_path:
    external: true

  vault_token:
    external: true