input {
    syslog {
        port => "5144"
        type => "syslog"
        tags => [ "pan_syslog" ]
    }
    syslog {
        port => "514"
        type => "syslog"
        tags => [ "pan_syslog" ]
    }
    syslog {
        port => "515"
        type => "fnet_syslog"
        tags => [ "fnet_syslog" ]
    }  
    syslog {
        port => "516"
        type => "clearpass"
        tags => [ "clearpass" ]
    }  
    beats {
        port => "550"
        type => "ESIEM_Host"
        tags => [ "ESIEM_Host" ]
        }
    beats {
        port => "5044"
        type => "winlogbeat"
        tags => [ "winlogbeat" ]
    }
    beats {
        port => "5045"
        type => "filebeat"
    }
    udp {
    port => 2055
    codec => netflow {
        versions => [9]
        target => "netflow"
        netflow_definitions => "/usr/share/logstash/config/pan_paloalto.yml"
    }
    type => "netflow"
    tags => [ "netflow" ]
    }

    udp {
    port => 9995
    codec => netflow {
        versions => [9]
        target => "netflow"
        netflow_definitions => "/usr/share/logstash/config/pan_paloalto.yml"
    }
    type => "netflow"
    tags => [ "netflow" ]
    }
}
