filter {

  if [type] == "netflow" {
    mutate {
      add_field => { "captured_host" => "%{host}" }
    }

    translate {
      field => "[netflow][input_snmp]"
      destination => "[netflow][input_interface]"
      dictionary_path => "/usr/share/logstash/pipeline/EnrichmentFiles/Netflow_Interface_Dictionaries.json"
      fallback => "unknown"
    }

    translate {
      field => "[netflow][output_snmp]"
      destination => "[netflow][output_interface]"
      dictionary_path => "/usr/share/logstash/pipeline/EnrichmentFiles/Netflow_Interface_Dictionaries.json"
      fallback => "unknown"
    }
  }
}
