filter {

    if "pan_syslog" in [tags] {

        # HIP log fields: https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/hip-match-log-fields.html
        if ([message] =~ /HIP/) {
            csv {
                source => "message"
                columns => [ 


		   "FUTURE_USE", "DROP_FIELD", "fw.serial_number", "event.type", "event.subtype", "FUTURE_USE", 
		   "timestamp", "fw.hip.source.user", "fw.vsys", "fw.hip.client.hostname", "fw.hip.host_os", "fw.hip.source.ip", 
		   "fw.hip.name", "event.repeat_count", "fw.hip.type", "FUTURE_USE", "FUTURE_USE", "event.sequence", 
		   "fw.log.fwd_panorama", "DROP_FIELD", "DROP_FIELD", "DROP_FIELD", "DROP_FIELD", "fw.vsys", 
		   "fw.name", "fw.vsys_id", "fw.hip.ipv6_source", "DROP_FIELD", "fw.hip.device_serial_number", 
		   "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", 
	 	   "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", "FUTURE_USE", "DROP_FIELD"

                ]   
            }   

            mutate {
                convert => [ "event.sequence", "integer" ]
    
                add_tag => ["pan_hip"]

                remove_field => ["FUTURE_USE", "DROP_FIELD"]

                add_field => { "related.host.name" => [ "%{fw.hip.client.hostname}" ] } 

                add_field => { "related.serial_number" => [ "%{fw.serial_number}",  "%{fw.hip.device_serial_number}" ] }

                add_field => { "related.ip" => [ "%{fw.traffic.source.ip}", "%{fw.traffic.destination.ip}" ] }
                add_field => { "related.destination.ip" => [ "%{fw.traffic.destination.ip}" ] }
                add_field => { "related.source.ip" => [ "%{fw.traffic.source.ip}" ] }

            }   
        } 
    }
}
