filter {

    if "pan_syslog" in [tags] {

        # System log fields: 
        if ([message] =~ /AUTH/) {
            csv {
                source => "message"
                columns => [ 
                    "FUTURE_USE", "Receive_Time", "Serial_Number", "Type", "Threat/Content_Type", "FUTURE_USE", "Generated_Time", "Virtual_System", "Source_IP", "User", "Normalize_User", "Object", "Authentication_Policy", "Repeat_Count", "Authentication_ID", "Vendor", "Log_Action", "Server_Profile", "Description", "Client_Type", "Event_Type", "Factor_Number", "Sequence_Number", "Action_Flags", "Device_Group_Hierarchy_1", "Device_Group_Hierarchy_2", "Device_Group_Hierarchy_3", "Device_Group_Hierarchy_4", "Virtual_System_Name", "Device_Name", "Virtual_System_ID", "Authentication_Protocol", "UUID_for_rule", "High_Resolution_Timestamp", "Source_Device_Category", "Source_Device_Profile", "Source_Device_Model", "Source_Device_Vendor", "Source_Device_OS_Family", "Source_Device_OS_Version", "Source_Hostname", "Source_Mac_Address", "Region", "FUTURE_USE", "User_Agent", "Session_ID"
                ]
            }
            
            # Exclude private IP addresses
            if [Source_Address_geo][ip] =~ /^10\.|^172\.(1[6-9]|2\d|3[01])\.|^192\.168\./ or [Destination_Address_geo][ip] =~ /^10\.|^172\.(1[6-9]|2\d|3[01])\.|^192\.168\./ {
                drop {}
            }
        

            geoip {
                source => "Source_IP"
                target => "Source_IP_geo"
            }

            mutate {
                add_tag => [ "pan_authentication"]
                remove_field => ["FUTURE_USE", "DROP_FIELD"]

            }
        }
    }
}
