filter {

    if "pan_syslog" in [tags] {

        # fw.userid.user-ID log fields: https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/user-id-log-fields.html
        if ([message] =~ /USERID/) {
            csv {
                source => "message"
                columns => [ 
                    "FUTURE_USER", "Receive_Time", "Serial_Number", "Type", "Threat/Content_Type", "FUTURE_USE", "Generated_Time", "Virtual_System", "Source_IP", "User", "Data_Source_Name", "Event_ID", "Repeat_Count", "Time_Out_Threshold", "Source_Port", "Destination_Port", "Data_Source", "Data_Source_Type", "Sequence_Number", "Action_Flags", "Device_Group_Hierarchy_Level_1", "Device_Group_Hierarchy_Level_2", "Device_Group_Hierarchy_Level_3", "Device_Group_Hierarchy_Level_4", "Virtual_System_Name", "Device_Name", "Virtual_System_ID", "Factor_Type", "Factor_Completion_Time", "Factor_Number", "User_Group_Flags", "User_by_Source", "Tag_Name", "High_Resolution_Timestamp"
                ]   
            }   

            mutate {
                convert => [ "Sequence_Number", "integer" ]
                add_tag => ["pan_userid"]
                remove_field => ["FUTURE_USE", "DROP_FIELD"]

            }   

        }
    }
}
