filter {

    if "pan_syslog" in [tags] {

        if ([message] =~ /DECRYPTION/) {
            csv {
                source => "message"
                columns => [ 
                    "FUTURE_USE", "Receive_Time", "Serial_Number", "Type", "Threat/Content_Type", "Config_Version", "Generate_Time", "Source_Address", "Destination_Address", "NAT_Source_IP", "NAT_Destination_IP", "Rule", "Source_User", "Destination_User", "Application", "Virtual_System", "Source_Zone", "Destination_Zone", "Inbound_Interface", "Outbound_Interface", "Log_Action", "Time_Logged", "Session_ID", "Repeat_Count", "Source_Port", "Destination_Port", "NAT_Source_Port", "NAT_Destination_Port", "Flags", "IP_Protocol", "Action", "Tunnel", "FUTURE_USE", "FUTURE_USE", "Source_VM_UUID", "Destination_VM_UUID", "UUID_for_rule", "Stage_for_Client_to_Firewall", "Stage_for_Firewall_to_Server", "TLS_Version", "Key_Exchange_Algorithm", "Encryption_Algorithm", "Hash_Algorithm", "Policy_Name", "Elliptic_Curve", "Error_Index", "Root_Status", "Chain_Status", "Proxy_Type", "Certificate_Serial_Number", "Fingerprint", "Certificate_Start_Date", "Certificate_End_Date", "Certificate_Version", "Certificate_Size", "Common_Name_Length", "Issuer_Common_Name_Length", "Root_Common_Name_Length", "SNI_Length", "Certificate_Flags", "Subject_Common_Name", "Issuer_Subject_Common_Name", "Root_Subject_Common_Name", "Server_Name_Indication", "Error", "Container_ID", "POD_Namespace", "POD_Name", "Source_External_Dynamic_List", "Destination_External_Dynamic_List", "Source_Dynamic_Address_Group", "Destination_Dynamic_Address_Group", "High_Res_Timestamp", "Source_Device_Category", "Source_Device_Profile", "Source_Device_Model", "Source_Device_Vendor", "Source_Device_OS_Family", "Source_Device_OS_Version", "Source_Hostname", "Source_Mac_Address", "Destination_Device_Category", "Destination_Device_Profile", "Destination_Device_Model", "Destination_Device_Vendor", "Destination_Device_OS_Family", "Destination_Device_OS_Version", "Destination_Hostname", "Destination_Mac_Address", "Sequence_Number", "Action_Flags", "Device_Group_Hierarchy_Level_1", "Device_Group_Hierarchy_Level_2", "Device_Group_Hierarchy_Level_3", "Device_Group_Hierarchy_Level_4", "Virtual_System_Name", "Device_Name", "Virtual_System_ID", "Application_Subcategory", "Application_Category", "Application_Technology", "Application_Risk", "Application_Characteristic", "Application_Container", "Application_SaaS", "Application_Sanctioned_State"
                ]
            }

            mutate {
                convert => [ "Sequence_Number", "integer" ]
                add_tag => ["pan_decryption"]
                remove_field => ["FUTURE_USE", "DROP_FIELD"]
            }

            fingerprint {
                concatenate_sources => true
                method => "SHA1"
                key => "logstash"
                source => [ "Source_Address", "Source_Port", "Destination_Address", "Destination_Port", "Session_ID" ]
                target => "Session_FingerPrint"
            }

        }
    }
}
