filter {

    if "pan_syslog" in [tags] {

        # IP Tag fields: https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/ip-tag-log-fields.html
        if ([message] =~ /IPTAG/) {
            csv {
                source => "message"
                columns => [ 

                   "FUTURE_USE", "DROP_FIELD", "fw.serial_number", "event.type", "event.subtype", "FUTURE_USE", "timestamp", 
                   "fw.vsys", "fw.iptag.source.ip", "fw.userid.tag_name", "event.id", "event.repeat_count", "DROP_FIELD", "fw.userid.source_system", 
                   "DROP_FIELD", "DROP_FIELD", "event.sequence", "fw.log.fwd_panorama", "DROP_FIELD", 
                   "DROP_FIELD", "DROP_FIELD", "DROP_FIELD", "fw.vsys", "fw.name", 
                   "fw.vsys_id", "DROP_FIELD"

                ]   
            }   

            mutate {
                convert => [ "event.sequence", "integer" ]
    
                add_tag => ["pan_iptag"]

                remove_field => ["FUTURE_USE", "DROP_FIELD"]

                add_field => { "related.serial_number" => [ "%{fw.serial_number}" ] }

                add_field => { "related.ip" => [ "%{fw.iptag.source.ip}" ] }
                add_field => { "related.source.ip" => [ "%{fw.iptag.source.ip}" ] }

            }   
        } 

    }
}
