filter {

    if "pan_syslog" in [tags] {

        # System log fields: 
        if ([message] =~ /CONFIG/) {
            csv {
                source => "message"
                columns => [ 
                    "FUTURE_USE", "Receive_Time", "Serial_Number", "Type", "Subtype", "FUTURE_USE", "Generated_Time", "Host", "Virtual_System", "Command", "Admin", "Client", "Result", "Configuration_Path", "Before_Change_Detail", "After_Change_Detail", "Sequence_Number", "Action_Flags", "Device_Group_Hierarchy_Level_1", "Device_Group_Hierarchy_Level_2", "Device_Group_Hierarchy_Level_3", "Device_Group_Hierarchy_Level_4", "Virtual_System_Name", "Device_Name", "Device_Group", "Audit_Comment", "FUTURE_USE", "High_Resolution_Timestamp"
                ]
            }

            mutate {
                add_tag => [ "pan_config" ]
                remove_field => ["FUTURE_USE", "DROP_FIELD"]
            }

        }
    }
}
