filter {

    if "pan_syslog" in [tags] {
        # GP log fields: https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields.html
        if ([message] =~ /GLOBALPROTECT/) {
            csv {
                source => "message"
                columns => [ 
                    "FUTURE_USE", "Receive_Time", "Serial_Number", "Type", "Threat/Content_Type", "FUTURE_USE", "Generated_Time", "Virtual_System", "Event_ID", "Stage", "Authentication_Method", "Tunnel_Type", "Source_User", "Source_Region", "Machine_Name", "Public_IP", "Public_IPv6", "Private_IP", "Private_IPv6", "Host_ID", "Serial_Number", "Client_Version", "Client_OS", "Client_OS_Version", "Repeat_Count", "Reason", "Error", "Description", "Status", "Location", "Login_Duration", "Connect_Method", "Error_Code", "Portal", "Sequence_Number", "Action_Flags", "High_Res_Timestamp", "Selection_Type", "Response_Time", "Priority", "Attempted_Gateways", "Gateway", "Device_Group_Hierarchy_Level_1", "Device_Group_Hierarchy_Level_2", "Device_Group_Hierarchy_Level_3", "Device_Group_Hierarchy_Level_4", "Virtual_System_Name", "Device_Name", "Virtual_System_ID"
                ]   
            }   

            geoip {
                source => "Public_IP"
                target => "Public_IP_geo"
            }    
            mutate {
                convert => [ "Sequence_Number", "integer" ]
                add_tag => ["pan_globalprotect"]
                remove_field => ["FUTURE_USE", "DROP_FIELD"]

            }   
        } 
    }
}
