filter {
  if "winlogbeat" in [tags] {

    if [source][ip] {
      mutate {
        copy => { "[source][ip]" => "[source][fqdn]" }
      }
      dns {
        reverse => [ "[source][fqdn]" ]
        action => "replace"
      }
    }

    if [host][ip] {
      mutate {
        copy => { "[host][ip]" => "[host][fqdn]" }
      }
    }

    if [related][ip] {
      split {
        field => "[related][ip]"
      }
      mutate {
        copy => { "[related][ip]" => "[related][fqdn]" }
      }
      dns {
        reverse => [ "[related][fqdn]" ]
        action => "replace"
      }
    }
  }
}